---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shivakumar-444/argo-cd-mine.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: httpd-ns
  syncPolicy:
    syncOptions:
    - CreateNAmespace: true
    automated:
      selfHeal: true
      prune: true
